services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=conder
      - DB_PASSWORD=wdrx4100
      - DB_DATABASE=blog
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
      # condition: service_healthy
    restart: always
    command: ['sh', '-c', 'sleep 20 && node dist/main.js'] # 增加延迟

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=wdrx4100
      - MYSQL_DATABASE=blog
      - MYSQL_USER=conder
      - MYSQL_PASSWORD=wdrx4100
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - '3306:3306'
    # healthcheck: # 强化健康检查
    #   test:
    #     [
    #       'CMD',
    #       'mysql',
    #       'ping',
    #       '-h',
    #       'localhost',
    #       '-u',
    #       'conder',
    #       '-pwdrx4100',
    #     ]
    #   interval: 5s
    #   timeout: 10s
    #   retries: 10
    #   start_period: 30s # 延长初始化等待时间
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/blog.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

volumes:
  db_data:
