version: '3.8'
services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=blog_user
      - DB_PASSWORD=your_password
      - DB_DATABASE=blog
      - JWT_SECRET=your-secret-key
    depends_on:
      - db
    restart: always

  db:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=blog
      - MYSQL_USER=blog_user
      - MYSQL_PASSWORD=your_password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/blog.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always

volumes:
  db_data:
