services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=wdrx4100
      - DB_DATABASE=blog
      - JWT_SECRET=MZPCcTuDFHkAb87fP7veY4YUwuwbI9t4tPcJC4E7pzg
      - TZ=Asia/Shanghai
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my-network
    restart: always
    # 入口脚本会处理数据库连接和初始化

  db:
    image: mysql:8.0.31
    environment:
      - MYSQL_ROOT_PASSWORD=wdrx4100
      - MYSQL_DATABASE=blog
      - TZ=Asia/Shanghai
    volumes:
      - ./db_data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '3306:3306'
    healthcheck: # 强化健康检查
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'root',
          '-pwdrx4100',
        ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/blog.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - my-network
    ports:
      - '80:80'
      - '443:443'
    restart: always

volumes:
  db_data:

networks:
  my-network:
    driver: bridge
