#!/bin/bash
TARGET="/var/www/blog-nest"
GIT_DIR="/var/www/blog-nest.git"
BRANCH="main"

while read oldrev newrev ref
do
    # 只有当推送的是main分支时才执行
    if [[ $ref = refs/heads/$BRANCH ]];
    then
        echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
        git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f
        cd $TARGET
        ./deploy.sh
    else
        echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
    fi
done 